name: gaussian_splatting
channels:
  - pytorch
  - nvidia/label/cuda-11.7.1
  - conda-forge
  - defaults
dependencies:
  # - cudatoolkit=11.6
  - cuda-toolkit
  - pytorch-cuda=11.7
  - plyfile=0.8.1
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.13.1
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
